<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #7b2cbf;
            border-bottom: 2px solid #7b2cbf;
            padding-bottom: 10px;
        }
        h2 {
            color: #333;
            margin-top: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #7b2cbf;
            color: white;
        }
        .footer {
            margin-top: 40px;
            font-size: 10px;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>{{ $report->title }}</h1>
    
    @if($report->description)
    <p><strong>Description:</strong> {{ $report->description }}</p>
    @endif

    <p><strong>Generated:</strong> {{ $report->generated_at ? $report->generated_at->format('Y-m-d H:i:s') : now()->format('Y-m-d H:i:s') }}</p>

    <h2>Report Data</h2>
    
    @if(!empty($data))
    <table>
        <thead>
            <tr>
                @foreach(array_keys($data[0]) as $header)
                <th>{{ ucwords(str_replace('_', ' ', $header)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
            <tr>
                @foreach($row as $cell)
                <td>{{ $cell }}</td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p>No data available for this report.</p>
    @endif

    <div class="footer">
        <p>Generated by CCIP - Crisis Communication and Information Platform</p>
        <p>Report ID: {{ $report->id }}</p>
    </div>
</body>
</html>

